# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}',
    './app'
  ]
  dir: 'demo-project'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: [
    'push',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}'
  ]
  dir: 'demo-project'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args: [
    'run',
    'services',
    'replace', 'notes-app-service.yaml',
    '--region', 'us-central1', # Specify your desired region
    '--project', '${PROJECT_ID}', # Specify the project ID
    '--quiet'
  ]
  dir: 'demo-project'

images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}'
